//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pixiv.Utilities.Ugoira.Download.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pixiv.Utilities.Ugoira.Download.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   /*!
        ///
        ///JSZip - A Javascript class for generating and reading zip files
        ///&lt;http://stuartk.com/jszip&gt;
        ///
        ///(c) 2009-2014 Stuart Knightley &lt;stuart [at] stuartk.com&gt;
        ///Dual licenced under the MIT license or GPLv3. See https://raw.github.com/Stuk/jszip/master/LICENSE.markdown.
        ///
        ///JSZip uses the library pako released under the MIT license :
        ///https://github.com/nodeca/pako/blob/master/LICENSE
        ///*/
        ///!function(a){if(&quot;object&quot;==typeof exports&amp;&amp;&quot;undefined&quot;!=typeof module)module.exports=a();else if(&quot;function&quot;==typeof define&amp;&amp;define.amd[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string jszip_min {
            get {
                return ResourceManager.GetString("jszip_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   var pixiv_login = function(id, pw)
        ///{
        ///	var root = document.getElementById(&apos;LoginComponent&apos;);
        ///	var idInput;
        ///	var pwInput;
        ///	var loginButton;
        ///
        ///	var findLogin = function(element)
        ///	{
        ///		var i = 0;
        ///		
        ///		for (i = 0; i &lt; element.childElementCount; i++)
        ///		{
        ///			var child = element.children[i];
        ///			if (child.attributes.type)
        ///			{
        ///				var childTypeValue = child.attributes.type.value.toLowerCase();
        ///				var childTagName = child.tagName.toLowerCase();
        ///				
        ///				if (childTagName == &apos;BUTTON&apos;.toLowerCase() &amp;&amp; [나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string pixiv_login {
            get {
                return ResourceManager.GetString("pixiv_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   var ugoira_data = function() {
        ///	var illustIDPrefix = &apos;illust_id=&apos;;
        ///	var illustID = document.location.href.substring(document.location.href.indexOf(illustIDPrefix) + illustIDPrefix.length);
        ///
        ///	var metaDataPrefix = &apos;https://www.pixiv.net/ajax/illust/&apos;;
        ///	var metaDataSuffix = &apos;/ugoira_meta&apos;;
        ///
        ///	var xhr1 = new XMLHttpRequest();
        ///	xhr1.open(&quot;get&quot;, metaDataPrefix + illustID, false);
        ///	xhr1.send();
        ///	
        ///	var xhr2 = new XMLHttpRequest();
        ///	xhr2.open(&quot;get&quot;, metaDataPrefix + illustID + metaDataSuffix, false);
        ///	xh[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ugoira_data {
            get {
                return ResourceManager.GetString("ugoira_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   var ugoira_zip = function (currentPosition, ugoiraCount) {
        ///	var title = document.querySelector(&quot;.work-info .title&quot;);
        ///	title.appendChild(document.createElement(&quot;br&quot;));
        ///	
        ///	[{
        ///		name: &quot;Zip&quot;,
        ///		data: pixiv.context.ugokuIllustData
        ///	}, {
        ///		name: &quot;ZipHQ&quot;,
        ///		data: pixiv.context.ugokuIllustFullscreenData
        ///	}].forEach(function (value) {
        ///		var elem, elemtxt, click;
        ///		click = function () {
        ///			if (&quot;removeEventListener&quot; in elem) {
        ///				elem.removeEventListener(&quot;click&quot;, click);
        ///			} else {
        ///				elem.detachEve[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ugoira_zip {
            get {
                return ResourceManager.GetString("ugoira_zip", resourceCulture);
            }
        }
    }
}
